<?
$PERM["personal"]["2"]="X";
$PERM["personal"]["6"]="X";
$PERM["personal"]["3"]="X";
$PERM["personal"]["4"]="X";
$PERM["personal"]["7"]="X";
$PERM["personal"]["5"]="X";
$PERM["personal"]["8"]="X";
$PERM["personal"]["*"]="X";
$PERM["catalog"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["/"]["*"]="R";
?>