<?php

namespace Sprint\Migration;


class Version20260831125750 extends Version{
    protected $author = "79177695923";

    protected $description = "";

    protected $moduleVersion = "5.6.1";

    /**
    * @throws Exceptions\HelperException
    * @return bool|void
    */
    public function up()
    {
        $helper = $this->getHelperManager();
                $helper->OrderProperties()->saveOrderProperty(array (
  'ID' => '14',
  'PERSON_TYPE_ID' => '1',
  'NAME' => 'Подъезд',
  'TYPE' => 'STRING',
  'REQUIRED' => 'N',
  'DEFAULT_VALUE' => '',
  'SORT' => '0',
  'USER_PROPS' => 'N',
  'IS_LOCATION' => 'N',
  'PROPS_GROUP_ID' => '2',
  'DESCRIPTION' => '',
  'IS_EMAIL' => 'N',
  'IS_PROFILE_NAME' => 'N',
  'IS_PAYER' => 'N',
  'IS_LOCATION4TAX' => 'N',
  'IS_FILTERED' => 'N',
  'CODE' => 'PODEZD',
  'IS_ZIP' => 'N',
  'IS_PHONE' => 'N',
  'IS_ADDRESS' => 'N',
  'IS_ADDRESS_FROM' => 'N',
  'IS_ADDRESS_TO' => 'N',
  'ACTIVE' => 'Y',
  'UTIL' => 'N',
  'INPUT_FIELD_LOCATION' => '0',
  'MULTIPLE' => 'N',
  'SETTINGS' => 
  array (
    'MINLENGTH' => '',
    'MAXLENGTH' => '',
    'PATTERN' => '',
    'MULTILINE' => 'N',
    'SIZE' => '',
  ),
  'ENTITY_REGISTRY_TYPE' => 'ORDER',
  'XML_ID' => '',
  'ENTITY_TYPE' => 'ORDER',
), 'code');
                    $helper->OrderProperties()->saveOrderProperty(array (
  'ID' => '15',
  'PERSON_TYPE_ID' => '1',
  'NAME' => 'Этаж',
  'TYPE' => 'NUMBER',
  'REQUIRED' => 'N',
  'DEFAULT_VALUE' => '',
  'SORT' => '0',
  'USER_PROPS' => 'N',
  'IS_LOCATION' => 'N',
  'PROPS_GROUP_ID' => '2',
  'DESCRIPTION' => '',
  'IS_EMAIL' => 'N',
  'IS_PROFILE_NAME' => 'N',
  'IS_PAYER' => 'N',
  'IS_LOCATION4TAX' => 'N',
  'IS_FILTERED' => 'N',
  'CODE' => 'ETAG',
  'IS_ZIP' => 'N',
  'IS_PHONE' => 'N',
  'IS_ADDRESS' => 'N',
  'IS_ADDRESS_FROM' => 'N',
  'IS_ADDRESS_TO' => 'N',
  'ACTIVE' => 'Y',
  'UTIL' => 'N',
  'INPUT_FIELD_LOCATION' => '0',
  'MULTIPLE' => 'N',
  'SETTINGS' => 
  array (
    'MIN' => '',
    'MAX' => '',
    'STEP' => '',
  ),
  'ENTITY_REGISTRY_TYPE' => 'ORDER',
  'XML_ID' => '',
  'ENTITY_TYPE' => 'ORDER',
), 'code');
                    $helper->OrderProperties()->saveOrderProperty(array (
  'ID' => '16',
  'PERSON_TYPE_ID' => '1',
  'NAME' => 'Квартира',
  'TYPE' => 'STRING',
  'REQUIRED' => 'N',
  'DEFAULT_VALUE' => '',
  'SORT' => '0',
  'USER_PROPS' => 'N',
  'IS_LOCATION' => 'N',
  'PROPS_GROUP_ID' => '2',
  'DESCRIPTION' => '',
  'IS_EMAIL' => 'N',
  'IS_PROFILE_NAME' => 'N',
  'IS_PAYER' => 'N',
  'IS_LOCATION4TAX' => 'N',
  'IS_FILTERED' => 'N',
  'CODE' => 'KVARTIRA',
  'IS_ZIP' => 'N',
  'IS_PHONE' => 'N',
  'IS_ADDRESS' => 'N',
  'IS_ADDRESS_FROM' => 'N',
  'IS_ADDRESS_TO' => 'N',
  'ACTIVE' => 'Y',
  'UTIL' => 'N',
  'INPUT_FIELD_LOCATION' => '0',
  'MULTIPLE' => 'N',
  'SETTINGS' => 
  array (
    'MINLENGTH' => '',
    'MAXLENGTH' => '',
    'PATTERN' => '',
    'MULTILINE' => 'N',
    'SIZE' => '',
  ),
  'ENTITY_REGISTRY_TYPE' => 'ORDER',
  'XML_ID' => '',
  'ENTITY_TYPE' => 'ORDER',
), 'code');
                    $helper->OrderProperties()->saveOrderProperty(array (
  'ID' => '17',
  'PERSON_TYPE_ID' => '1',
  'NAME' => 'Код домофона',
  'TYPE' => 'STRING',
  'REQUIRED' => 'N',
  'DEFAULT_VALUE' => '',
  'SORT' => '0',
  'USER_PROPS' => 'N',
  'IS_LOCATION' => 'N',
  'PROPS_GROUP_ID' => '2',
  'DESCRIPTION' => '',
  'IS_EMAIL' => 'N',
  'IS_PROFILE_NAME' => 'N',
  'IS_PAYER' => 'N',
  'IS_LOCATION4TAX' => 'N',
  'IS_FILTERED' => 'N',
  'CODE' => 'DOMOFON',
  'IS_ZIP' => 'N',
  'IS_PHONE' => 'N',
  'IS_ADDRESS' => 'N',
  'IS_ADDRESS_FROM' => 'N',
  'IS_ADDRESS_TO' => 'N',
  'ACTIVE' => 'Y',
  'UTIL' => 'N',
  'INPUT_FIELD_LOCATION' => '0',
  'MULTIPLE' => 'N',
  'SETTINGS' => 
  array (
    'MINLENGTH' => '',
    'MAXLENGTH' => '',
    'PATTERN' => '',
    'MULTILINE' => 'N',
    'SIZE' => '',
  ),
  'ENTITY_REGISTRY_TYPE' => 'ORDER',
  'XML_ID' => '',
  'ENTITY_TYPE' => 'ORDER',
), 'code');
                    $helper->OrderProperties()->saveOrderProperty(array (
  'ID' => '18',
  'PERSON_TYPE_ID' => '1',
  'NAME' => 'ID ресторана',
  'TYPE' => 'STRING',
  'REQUIRED' => 'N',
  'DEFAULT_VALUE' => '',
  'SORT' => '0',
  'USER_PROPS' => 'N',
  'IS_LOCATION' => 'N',
  'PROPS_GROUP_ID' => '2',
  'DESCRIPTION' => '',
  'IS_EMAIL' => 'N',
  'IS_PROFILE_NAME' => 'N',
  'IS_PAYER' => 'N',
  'IS_LOCATION4TAX' => 'N',
  'IS_FILTERED' => 'N',
  'CODE' => 'RESTORAN_ID',
  'IS_ZIP' => 'N',
  'IS_PHONE' => 'N',
  'IS_ADDRESS' => 'N',
  'IS_ADDRESS_FROM' => 'N',
  'IS_ADDRESS_TO' => 'N',
  'ACTIVE' => 'Y',
  'UTIL' => 'N',
  'INPUT_FIELD_LOCATION' => '0',
  'MULTIPLE' => 'N',
  'SETTINGS' => 
  array (
    'MINLENGTH' => '',
    'MAXLENGTH' => '',
    'PATTERN' => '',
    'MULTILINE' => 'N',
    'SIZE' => '',
  ),
  'ENTITY_REGISTRY_TYPE' => 'ORDER',
  'XML_ID' => '',
  'ENTITY_TYPE' => 'ORDER',
), 'code');
                    $helper->OrderProperties()->saveOrderProperty(array (
  'ID' => '19',
  'PERSON_TYPE_ID' => '1',
  'NAME' => 'Название ресторана',
  'TYPE' => 'STRING',
  'REQUIRED' => 'N',
  'DEFAULT_VALUE' => '',
  'SORT' => '0',
  'USER_PROPS' => 'N',
  'IS_LOCATION' => 'N',
  'PROPS_GROUP_ID' => '2',
  'DESCRIPTION' => '',
  'IS_EMAIL' => 'N',
  'IS_PROFILE_NAME' => 'N',
  'IS_PAYER' => 'N',
  'IS_LOCATION4TAX' => 'N',
  'IS_FILTERED' => 'N',
  'CODE' => 'NAME_RESTORAN',
  'IS_ZIP' => 'N',
  'IS_PHONE' => 'N',
  'IS_ADDRESS' => 'N',
  'IS_ADDRESS_FROM' => 'N',
  'IS_ADDRESS_TO' => 'N',
  'ACTIVE' => 'Y',
  'UTIL' => 'N',
  'INPUT_FIELD_LOCATION' => '0',
  'MULTIPLE' => 'N',
  'SETTINGS' => 
  array (
    'MINLENGTH' => '',
    'MAXLENGTH' => '',
    'PATTERN' => '',
    'MULTILINE' => 'N',
    'SIZE' => '',
  ),
  'ENTITY_REGISTRY_TYPE' => 'ORDER',
  'XML_ID' => '',
  'ENTITY_TYPE' => 'ORDER',
), 'code');
        }
}
