CREATE TABLE IF NOT EXISTS mib_smartconsultant_embedding (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SEARCH_CONTENT_ID INT NOT NULL,
    EMBEDDING MEDIUMBLOB NOT NULL,
    TEXT_HASH CHAR(32) NOT NULL,
    INDEXED_AT DATETIME NOT NULL,
    UNIQUE KEY ux_search_content (SEARCH_CONTENT_ID),
    KEY ix_indexed_at (INDEXED_AT)
);
